modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "eveningstarlib"
displayName = "Evening Star Lib"
version = "${version}"
displayURL = ""
logoFile = "assets/icon.png"
authors = "VesMaybeVesper"
description = ''''''

[[mixins]]
config = "eveningstarlib.mixins.json"

[[dependencies.eveningstarlib]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eveningstarlib]]
modId = "minecraft"
type = "required"
